### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by chumeng666** [bravekingzhang/text2viedo#5]
CompletedProcess(args=['edge-tts', '--voice', 'zh-CN-XiaoyiNeural', '--text', '天空蔚蓝', '--write-media', 'voices/1695236088-pollinations-ai.mp3', '--write-subtitles', 'voices/1695236088-pollinations-ai.mp3.vtt'], returncode=0)
voices/1695236088-pollinations-ai.mp3.vtt
Building prefix dict from the default dictionary ...
Dumping model to file cache /tmp/jieba.cache
Loading model cost 1.706 seconds.
Prefix dict has been built successfully.
[2023-09-21 02:54:54,993] ERROR in app: Exception on /convert [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 21, in convert_text_to_video
    video_path = convertTextToVideo(validate_model(model), text)
  File "/root/tts/text2video/text_to_video.py", line 126, in convertTextToVideo
    add_text_to_image(draw_text, image_path,
  File "/root/tts/text2video/add_text_to_image.py", line 30, in add_text_to_image
    if draw.textsize(current_line  + word, font=font)[0] <= target_size[0] - 2 * padding:
AttributeError: 'ImageDraw' object has no attribute 'textsize'
127.0.0.1 - - [21/Sep/2023 02:54:55] "POST /convert HTTP/1.1" 500 -

**Comment by XuWink** [comment]
edge-tts需要自己安装吗？

**Comment by bravekingzhang** [comment]
支持docker一键启动
