### ISSUE TITLE
ModuleNotFoundError: No module named 'dotenv'

### ISSUE THREAD

**Issue by jon1301** [bravekingzhang/text2viedo#7]
python3.10 app.py
Traceback (most recent call last):
  File "/Users/wangwenjie/Documents/text2video/app.py", line 3, in <module>
    from text_to_video import convertTextToVideo
  File "/Users/wangwenjie/Documents/text2video/text_to_video.py", line 7, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

然后我执行了：pip install python-dotenv
还是不行

**Comment by katorly** [comment]
我这边提示需要执行`pip install --use-pep517 dotenv`，但仍然安装失败。

感谢楼主，执行`pip install python-dotenv`就可以了。😄

如果楼主没执行过`pip install --use-pep517 dotenv`的话可以试试该指令。

**Comment by bravekingzhang** [comment]
支持 docker 一键启动了。
